# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/aasha',
                'doc_host': 'https://bkowshik.github.io',
                'git_url': 'https://github.com/bkowshik/aasha',
                'lib_path': 'aasha'},
  'syms': {'aasha.core': {'aasha.core.foo': ('core.html#foo', 'aasha/core.py')}}}
