"""Process data from FIFA."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_fifa.ipynb.

# %% auto 0
__all__ = ['fetch_fifa_rankings', 'write_fifa_rankings', 'parse_fifa_rankings']

# %% ../nbs/01_fifa.ipynb 3
def fetch_fifa_rankings(gender):
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'}

    if gender == 'men':
        url = 'https://inside.fifa.com/api/ranking-overview?locale=en&dateId=id14597&rankingType=football'
    else:
        url = 'https://inside.fifa.com/api/ranking-overview?locale=en&dateId=ranking_20250306&rankingType=football'

    response = requests.get(url, headers = headers)
    if response.status_code == 200:
        data = response.json()
        return data
    else:
        print('Error fetching data: ', response.status_code)
        return None

# %% ../nbs/01_fifa.ipynb 4
def write_fifa_rankings(rankings, filepath):
    with open(filepath, 'w') as f:
        json.dump(rankings, f, indent=4)

# %% ../nbs/01_fifa.ipynb 5
def parse_fifa_rankings(rankings, country = 'India'):
    rank = [item for item in rankings['rankings'] if item['rankingItem']['name'] == country][0]
    return rank
