"""Process data from FIFA."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_fifa.ipynb.

# %% auto 0
__all__ = ['fetch_fifa_rankings', 'write_fifa_rankings', 'parse_fifa_rankings']

# %% ../nbs/01_fifa.ipynb 3
def fetch_fifa_rankings(gender):
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'}

    if gender == 'men':
        url = 'https://inside.fifa.com/api/rankings/by-country?gender=1&countryCode=IND&locale=en'
    else:
        url = 'https://inside.fifa.com/api/rankings/by-country?gender=2&countryCode=IND&locale=en'

    response = requests.get(url, headers = headers)
    if response.status_code == 200:
        data = response.json()
        return data
    else:
        print('Error fetching data: ', response.status_code)
        return None

# %% ../nbs/01_fifa.ipynb 4
def write_fifa_rankings(response, filepath):
    with open(filepath, 'w') as f:
        json.dump(response, f, indent=4)

# %% ../nbs/01_fifa.ipynb 5
def parse_fifa_rankings(response):
    df = pd.json_normalize(response['rankings'])

    # Clean column names: convert to lowercase and replace spaces or special characters with underscores
    df.columns = df.columns.str.lower().str.replace(' ', '_').str.replace(r'[^\w]', '_', regex=True)

    df['pubdate'] = pd.to_datetime(df['pubdate'])
    df.sort_values('pubdate', ascending=True, inplace=True)

    return df
